services:

  n8n:
    image: n8nio/n8n:local
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=host.docker.internal
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n-local
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=rootpassword
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_PUSH_BACKEND=sse
      - N8N_ENCRYPTION_KEY=1jk90H2qp/UUpbp7626C3DhAd4h/Qp6x
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
